parsers:
  # CXXParser should always put first
  - name: CXXParser
    package: '@agoraio-extensions/cxx-parser'
    args:
      includeHeaderDirs:
        - '@agoraio-extensions/terra_shared_configs:headers/rtc_4.2.3/include'
      parseFiles:
        include:
          - '@agoraio-extensions/terra_shared_configs:headers/rtc_4.2.3/include/*.h'
        exclude:
          - '@agoraio-extensions/terra_shared_configs:headers/rtc_4.2.3/include/time_utils.h'
          - '@agoraio-extensions/terra_shared_configs:headers/rtc_4.2.3/include/IAgoraMediaComponentFactory.h'

  - name: RemoveNodeParser
    package: '@agoraio-extensions/terra_shared_configs'
    args:
      ignoreDefaultConfig: true
      configFilePath: ./remove_node_list.ts
  - name: PointerToArrayParser
    package: '@agoraio-extensions/terra_shared_configs'
  - name: IrisApiIdParser
    package: '@agoraio-extensions/terra_shared_configs'
  - name: UpdateSimpleTypeParser
    package: '@agoraio-extensions/terra_shared_configs'
  - name: ReturnTypeParser
    package: '@agoraio-extensions/terra_shared_configs'
  - name: FixEnumConstantParser
    package: '@agoraio-extensions/terra_shared_configs'
  - name: MergeNodeParser
    package: '@agoraio-extensions/terra_shared_configs'
    args:
      configFilePath: ./merge_node_list.ts
      ignoreDefaultConfig: true
  - name: OrderNodeParser
    package: '@agoraio-extensions/terra_shared_configs'

  - name: UpdateSimpleTypeParser
    package: '@agoraio-extensions/terra_shared_configs'
    args:
      parserDefaultValue: true
      ignoreDefaultConfig: true
      configFilePath: '@agoraio-extensions/terra_shared_configs:configs/rtc/ts/c_to_ts_config.ts'

renderers:
  - path: ../binding.ts
  - path: ../binding_test.ts
  - path: ../api-type.ts
