include: shared:rtc_4.2.3/shared_configs.yaml

language: ts

renderers:
  - ../index.ts
parsers:
  - PointerToArrayParser:
      configJsonFilePath: ./config/pointer_to_array.json
  - OrderNodeParser
  - FixEnumConstantParser
  - UpdateSimpleTypeParser:
      configJsonFilePath: ./config/param_type_list.json
  - RemoveNodeParser:
      configJsonFilePath: ./config/remove_node_list.json
