include: shared:rtc_4.2.3/shared_configs.yaml

language: ts

renderers:
  - ../index.ts
parsers:
  - OrderNodeParser
  - FixEnumConstantParser
  - UpdateSimpleTypeParser:
      configJsonFilePath: /Users/guoxianzhe/agora/iris_web/scripts/terra/config/param_type_list.json
  - RemoveNodeParser:
      configJsonFilePath: /Users/guoxianzhe/agora/iris_web/scripts/terra/config/remove_node_list.json
