/// Generated by terra, DO NOT MODIFY BY HAND.

import { ERROR_CODE_TYPE, ILocalSpatialAudioEngine } from '@iris/native-rtc';
import { ApiParam, CallApiReturnType } from 'iris-web-core';

import { IrisRtcEngine } from '../engine/IrisRtcEngine';
import { AgoraConsole } from '../util/AgoraConsole';

export class ILocalSpatialAudioEngineDispatch
  implements ILocalSpatialAudioEngine {
  _engine: IrisRtcEngine = null;

  constructor(engine: IrisRtcEngine) {
    this._engine = engine;
  }
  // @ts-ignore
  release(): CallApiReturnType {
    AgoraConsole.warn(
      'LocalSpatialAudioEngine_release not supported in this platform!'
    );
    return this._engine.returnResult(false, -ERROR_CODE_TYPE.ERR_NOT_SUPPORTED);
  }

  // @ts-ignore
  initialize_cf94fbf(): CallApiReturnType {
    AgoraConsole.warn(
      'LocalSpatialAudioEngine_initialize_cf94fbf not supported in this platform!'
    );
    return this._engine.returnResult(false, -ERROR_CODE_TYPE.ERR_NOT_SUPPORTED);
  }

  // @ts-ignore
  updateRemotePosition_adc0909(apiParam: ApiParam): CallApiReturnType {
    AgoraConsole.warn(
      'LocalSpatialAudioEngine_updateRemotePosition_adc0909 not supported in this platform!'
    );
    return this._engine.returnResult(false, -ERROR_CODE_TYPE.ERR_NOT_SUPPORTED);
  }

  // @ts-ignore
  updateRemotePositionEx_f0252d9(apiParam: ApiParam): CallApiReturnType {
    AgoraConsole.warn(
      'LocalSpatialAudioEngine_updateRemotePositionEx_f0252d9 not supported in this platform!'
    );
    return this._engine.returnResult(false, -ERROR_CODE_TYPE.ERR_NOT_SUPPORTED);
  }

  // @ts-ignore
  removeRemotePosition_c8d091a(apiParam: ApiParam): CallApiReturnType {
    AgoraConsole.warn(
      'LocalSpatialAudioEngine_removeRemotePosition_c8d091a not supported in this platform!'
    );
    return this._engine.returnResult(false, -ERROR_CODE_TYPE.ERR_NOT_SUPPORTED);
  }

  // @ts-ignore
  removeRemotePositionEx_58a9850(apiParam: ApiParam): CallApiReturnType {
    AgoraConsole.warn(
      'LocalSpatialAudioEngine_removeRemotePositionEx_58a9850 not supported in this platform!'
    );
    return this._engine.returnResult(false, -ERROR_CODE_TYPE.ERR_NOT_SUPPORTED);
  }

  // @ts-ignore
  clearRemotePositionsEx_c81e1a4(apiParam: ApiParam): CallApiReturnType {
    AgoraConsole.warn(
      'LocalSpatialAudioEngine_clearRemotePositionsEx_c81e1a4 not supported in this platform!'
    );
    return this._engine.returnResult(false, -ERROR_CODE_TYPE.ERR_NOT_SUPPORTED);
  }

  // @ts-ignore
  updateSelfPositionEx_502183a(apiParam: ApiParam): CallApiReturnType {
    AgoraConsole.warn(
      'LocalSpatialAudioEngine_updateSelfPositionEx_502183a not supported in this platform!'
    );
    return this._engine.returnResult(false, -ERROR_CODE_TYPE.ERR_NOT_SUPPORTED);
  }

  // @ts-ignore
  setMaxAudioRecvCount_46f8ab7(apiParam: ApiParam): CallApiReturnType {
    AgoraConsole.warn(
      'LocalSpatialAudioEngine_setMaxAudioRecvCount_46f8ab7 not supported in this platform!'
    );
    return this._engine.returnResult(false, -ERROR_CODE_TYPE.ERR_NOT_SUPPORTED);
  }

  // @ts-ignore
  setAudioRecvRange_685e803(apiParam: ApiParam): CallApiReturnType {
    AgoraConsole.warn(
      'LocalSpatialAudioEngine_setAudioRecvRange_685e803 not supported in this platform!'
    );
    return this._engine.returnResult(false, -ERROR_CODE_TYPE.ERR_NOT_SUPPORTED);
  }

  // @ts-ignore
  setDistanceUnit_685e803(apiParam: ApiParam): CallApiReturnType {
    AgoraConsole.warn(
      'LocalSpatialAudioEngine_setDistanceUnit_685e803 not supported in this platform!'
    );
    return this._engine.returnResult(false, -ERROR_CODE_TYPE.ERR_NOT_SUPPORTED);
  }

  // @ts-ignore
  updateSelfPosition_9c9930f(apiParam: ApiParam): CallApiReturnType {
    AgoraConsole.warn(
      'LocalSpatialAudioEngine_updateSelfPosition_9c9930f not supported in this platform!'
    );
    return this._engine.returnResult(false, -ERROR_CODE_TYPE.ERR_NOT_SUPPORTED);
  }

  // @ts-ignore
  updatePlayerPositionInfo_b37c59d(apiParam: ApiParam): CallApiReturnType {
    AgoraConsole.warn(
      'LocalSpatialAudioEngine_updatePlayerPositionInfo_b37c59d not supported in this platform!'
    );
    return this._engine.returnResult(false, -ERROR_CODE_TYPE.ERR_NOT_SUPPORTED);
  }

  // @ts-ignore
  setParameters_3a2037f(apiParam: ApiParam): CallApiReturnType {
    AgoraConsole.warn(
      'LocalSpatialAudioEngine_setParameters_3a2037f not supported in this platform!'
    );
    return this._engine.returnResult(false, -ERROR_CODE_TYPE.ERR_NOT_SUPPORTED);
  }

  // @ts-ignore
  muteLocalAudioStream_5039d15(apiParam: ApiParam): CallApiReturnType {
    AgoraConsole.warn(
      'LocalSpatialAudioEngine_muteLocalAudioStream_5039d15 not supported in this platform!'
    );
    return this._engine.returnResult(false, -ERROR_CODE_TYPE.ERR_NOT_SUPPORTED);
  }

  // @ts-ignore
  muteAllRemoteAudioStreams_5039d15(apiParam: ApiParam): CallApiReturnType {
    AgoraConsole.warn(
      'LocalSpatialAudioEngine_muteAllRemoteAudioStreams_5039d15 not supported in this platform!'
    );
    return this._engine.returnResult(false, -ERROR_CODE_TYPE.ERR_NOT_SUPPORTED);
  }

  // @ts-ignore
  muteRemoteAudioStream_dbdc15a(apiParam: ApiParam): CallApiReturnType {
    AgoraConsole.warn(
      'LocalSpatialAudioEngine_muteRemoteAudioStream_dbdc15a not supported in this platform!'
    );
    return this._engine.returnResult(false, -ERROR_CODE_TYPE.ERR_NOT_SUPPORTED);
  }

  // @ts-ignore
  setRemoteAudioAttenuation_74c3e98(apiParam: ApiParam): CallApiReturnType {
    AgoraConsole.warn(
      'LocalSpatialAudioEngine_setRemoteAudioAttenuation_74c3e98 not supported in this platform!'
    );
    return this._engine.returnResult(false, -ERROR_CODE_TYPE.ERR_NOT_SUPPORTED);
  }

  // @ts-ignore
  setZones_414a27e(apiParam: ApiParam): CallApiReturnType {
    AgoraConsole.warn(
      'LocalSpatialAudioEngine_setZones_414a27e not supported in this platform!'
    );
    return this._engine.returnResult(false, -ERROR_CODE_TYPE.ERR_NOT_SUPPORTED);
  }

  // @ts-ignore
  setPlayerAttenuation_a15bc51(apiParam: ApiParam): CallApiReturnType {
    AgoraConsole.warn(
      'LocalSpatialAudioEngine_setPlayerAttenuation_a15bc51 not supported in this platform!'
    );
    return this._engine.returnResult(false, -ERROR_CODE_TYPE.ERR_NOT_SUPPORTED);
  }

  // @ts-ignore
  clearRemotePositions(): CallApiReturnType {
    AgoraConsole.warn(
      'LocalSpatialAudioEngine_clearRemotePositions not supported in this platform!'
    );
    return this._engine.returnResult(false, -ERROR_CODE_TYPE.ERR_NOT_SUPPORTED);
  }
}
