/// Generated by terra, DO NOT MODIFY BY HAND.

import {
  ERROR_CODE_TYPE,
  IMusicContentCenter,
  IMusicPlayer,
  MusicChartCollection,
  MusicChartInfo,
  MusicCollection,
  MusicContentCenterStatusCode,
  PreloadStatusCode,
} from '@iris/native-rtc';
import { ApiParam, CallApiReturnType } from 'iris-web-core';

import { IrisRtcEngine } from '../engine/IrisRtcEngine';
import { AgoraConsole } from '../util/AgoraConsole';

import { IMediaPlayerDispatch } from './IAgoraMediaPlayerDispatch';

export class MusicChartCollectionDispatch implements MusicChartCollection {
  _engine: IrisRtcEngine = null;

  constructor(engine: IrisRtcEngine) {
    this._engine = engine;
  }
  // @ts-ignore
  getCount(): CallApiReturnType {
    AgoraConsole.warn('getCount not supported in this platform!');
    return this._engine.returnResult(false, -ERROR_CODE_TYPE.ERR_NOT_SUPPORTED);
  }

  // @ts-ignore
  get_46f8ab7(apiParam: ApiParam): CallApiReturnType {
    AgoraConsole.warn('get_46f8ab7 not supported in this platform!');
    return this._engine.returnResult(false, -ERROR_CODE_TYPE.ERR_NOT_SUPPORTED);
  }
}

export class MusicCollectionDispatch implements MusicCollection {
  _engine: IrisRtcEngine = null;

  constructor(engine: IrisRtcEngine) {
    this._engine = engine;
  }
  // @ts-ignore
  getCount(): CallApiReturnType {
    AgoraConsole.warn('getCount not supported in this platform!');
    return this._engine.returnResult(false, -ERROR_CODE_TYPE.ERR_NOT_SUPPORTED);
  }

  // @ts-ignore
  getTotal(): CallApiReturnType {
    AgoraConsole.warn('getTotal not supported in this platform!');
    return this._engine.returnResult(false, -ERROR_CODE_TYPE.ERR_NOT_SUPPORTED);
  }

  // @ts-ignore
  getPage(): CallApiReturnType {
    AgoraConsole.warn('getPage not supported in this platform!');
    return this._engine.returnResult(false, -ERROR_CODE_TYPE.ERR_NOT_SUPPORTED);
  }

  // @ts-ignore
  getPageSize(): CallApiReturnType {
    AgoraConsole.warn('getPageSize not supported in this platform!');
    return this._engine.returnResult(false, -ERROR_CODE_TYPE.ERR_NOT_SUPPORTED);
  }

  // @ts-ignore
  getMusic_8fcdcef(apiParam: ApiParam): CallApiReturnType {
    AgoraConsole.warn('getMusic_8fcdcef not supported in this platform!');
    return this._engine.returnResult(false, -ERROR_CODE_TYPE.ERR_NOT_SUPPORTED);
  }
}

export class IMusicContentCenterEventHandler {
  _engine: IrisRtcEngine = null;

  constructor(engine: IrisRtcEngine) {
    this._engine = engine;
  }

  notifyEvent(param: ApiParam): void {
    this._engine.irisEventHandlerManager.notifyEvent('RtcEngine', param);
  }

  onMusicChartsResult_3597d7e(
    requestId: string,
    result: MusicChartInfo[],
    errorCode: MusicContentCenterStatusCode
  ): void {
    AgoraConsole.warn(
      'onMusicChartsResult_3597d7e not supported in this platform!'
    );
    this._engine.returnResult(false, -ERROR_CODE_TYPE.ERR_NOT_SUPPORTED);
  }

  onMusicCollectionResult_1517101(
    requestId: string,
    result: MusicCollection,
    errorCode: MusicContentCenterStatusCode
  ): void {
    AgoraConsole.warn(
      'onMusicCollectionResult_1517101 not supported in this platform!'
    );
    this._engine.returnResult(false, -ERROR_CODE_TYPE.ERR_NOT_SUPPORTED);
  }

  onLyricResult_981e37c(
    requestId: string,
    songCode: number,
    lyricUrl: string,
    errorCode: MusicContentCenterStatusCode
  ): void {
    AgoraConsole.warn('onLyricResult_981e37c not supported in this platform!');
    this._engine.returnResult(false, -ERROR_CODE_TYPE.ERR_NOT_SUPPORTED);
  }

  onSongSimpleInfoResult_981e37c(
    requestId: string,
    songCode: number,
    simpleInfo: string,
    errorCode: MusicContentCenterStatusCode
  ): void {
    AgoraConsole.warn(
      'onSongSimpleInfoResult_981e37c not supported in this platform!'
    );
    this._engine.returnResult(false, -ERROR_CODE_TYPE.ERR_NOT_SUPPORTED);
  }

  onPreLoadEvent_562c799(
    requestId: string,
    songCode: number,
    percent: number,
    lyricUrl: string,
    status: PreloadStatusCode,
    errorCode: MusicContentCenterStatusCode
  ): void {
    AgoraConsole.warn('onPreLoadEvent_562c799 not supported in this platform!');
    this._engine.returnResult(false, -ERROR_CODE_TYPE.ERR_NOT_SUPPORTED);
  }
}

export class IMusicPlayerDispatch extends IMediaPlayerDispatch
  implements IMusicPlayer {
  _engine: IrisRtcEngine = null;

  constructor(engine: IrisRtcEngine) {
    super(engine);
    this._engine = engine;
  }
}

export class IMusicContentCenterDispatch implements IMusicContentCenter {
  _engine: IrisRtcEngine = null;

  constructor(engine: IrisRtcEngine) {
    this._engine = engine;
  }
  // @ts-ignore
  initialize_df70304(apiParam: ApiParam): CallApiReturnType {
    AgoraConsole.warn('initialize_df70304 not supported in this platform!');
    return this._engine.returnResult(false, -ERROR_CODE_TYPE.ERR_NOT_SUPPORTED);
  }

  // @ts-ignore
  renewToken_3a2037f(apiParam: ApiParam): CallApiReturnType {
    AgoraConsole.warn('renewToken_3a2037f not supported in this platform!');
    return this._engine.returnResult(false, -ERROR_CODE_TYPE.ERR_NOT_SUPPORTED);
  }

  // @ts-ignore
  release(): CallApiReturnType {
    AgoraConsole.warn('release not supported in this platform!');
    return this._engine.returnResult(false, -ERROR_CODE_TYPE.ERR_NOT_SUPPORTED);
  }

  // @ts-ignore
  registerEventHandler_ae49451(apiParam: ApiParam): CallApiReturnType {
    AgoraConsole.warn(
      'registerEventHandler_ae49451 not supported in this platform!'
    );
    return this._engine.returnResult(false, -ERROR_CODE_TYPE.ERR_NOT_SUPPORTED);
  }

  // @ts-ignore
  unregisterEventHandler(apiParam: ApiParam): CallApiReturnType {
    AgoraConsole.warn('unregisterEventHandler not supported in this platform!');
    return this._engine.returnResult(false, -ERROR_CODE_TYPE.ERR_NOT_SUPPORTED);
  }

  // @ts-ignore
  createMusicPlayer(): CallApiReturnType {
    AgoraConsole.warn('createMusicPlayer not supported in this platform!');
    return this._engine.returnResult(false, -ERROR_CODE_TYPE.ERR_NOT_SUPPORTED);
  }

  // @ts-ignore
  getMusicCharts_66d4ecd(apiParam: ApiParam): CallApiReturnType {
    AgoraConsole.warn('getMusicCharts_66d4ecd not supported in this platform!');
    return this._engine.returnResult(false, -ERROR_CODE_TYPE.ERR_NOT_SUPPORTED);
  }

  // @ts-ignore
  getMusicCollectionByMusicChartId_8cd0b4d(
    apiParam: ApiParam
  ): CallApiReturnType {
    AgoraConsole.warn(
      'getMusicCollectionByMusicChartId_8cd0b4d not supported in this platform!'
    );
    return this._engine.returnResult(false, -ERROR_CODE_TYPE.ERR_NOT_SUPPORTED);
  }

  // @ts-ignore
  searchMusic_3f8cf09(apiParam: ApiParam): CallApiReturnType {
    AgoraConsole.warn('searchMusic_3f8cf09 not supported in this platform!');
    return this._engine.returnResult(false, -ERROR_CODE_TYPE.ERR_NOT_SUPPORTED);
  }

  // @ts-ignore
  preload_bd5a5a3(apiParam: ApiParam): CallApiReturnType {
    AgoraConsole.warn('preload_bd5a5a3 not supported in this platform!');
    return this._engine.returnResult(false, -ERROR_CODE_TYPE.ERR_NOT_SUPPORTED);
  }

  // @ts-ignore
  preload_d3baeab(apiParam: ApiParam): CallApiReturnType {
    AgoraConsole.warn('preload_d3baeab not supported in this platform!');
    return this._engine.returnResult(false, -ERROR_CODE_TYPE.ERR_NOT_SUPPORTED);
  }

  // @ts-ignore
  removeCache_f631116(apiParam: ApiParam): CallApiReturnType {
    AgoraConsole.warn('removeCache_f631116 not supported in this platform!');
    return this._engine.returnResult(false, -ERROR_CODE_TYPE.ERR_NOT_SUPPORTED);
  }

  // @ts-ignore
  getCaches_c4f9978(apiParam: ApiParam): CallApiReturnType {
    AgoraConsole.warn('getCaches_c4f9978 not supported in this platform!');
    return this._engine.returnResult(false, -ERROR_CODE_TYPE.ERR_NOT_SUPPORTED);
  }

  // @ts-ignore
  isPreloaded_f631116(apiParam: ApiParam): CallApiReturnType {
    AgoraConsole.warn('isPreloaded_f631116 not supported in this platform!');
    return this._engine.returnResult(false, -ERROR_CODE_TYPE.ERR_NOT_SUPPORTED);
  }

  // @ts-ignore
  getLyric_5ab5efd(apiParam: ApiParam): CallApiReturnType {
    AgoraConsole.warn('getLyric_5ab5efd not supported in this platform!');
    return this._engine.returnResult(false, -ERROR_CODE_TYPE.ERR_NOT_SUPPORTED);
  }

  // @ts-ignore
  getSongSimpleInfo_d3baeab(apiParam: ApiParam): CallApiReturnType {
    AgoraConsole.warn(
      'getSongSimpleInfo_d3baeab not supported in this platform!'
    );
    return this._engine.returnResult(false, -ERROR_CODE_TYPE.ERR_NOT_SUPPORTED);
  }

  // @ts-ignore
  getInternalSongCode_3a3d1e7(apiParam: ApiParam): CallApiReturnType {
    AgoraConsole.warn(
      'getInternalSongCode_3a3d1e7 not supported in this platform!'
    );
    return this._engine.returnResult(false, -ERROR_CODE_TYPE.ERR_NOT_SUPPORTED);
  }
}
