/// Generated by terra, DO NOT MODIFY BY HAND.

import {
  CacheStatistics,
  MEDIA_PLAYER_EVENT,
  MEDIA_PLAYER_REASON,
  MEDIA_PLAYER_STATE,
  PLAYER_PRELOAD_EVENT,
  PlayerPlaybackStats,
  PlayerUpdatedInfo,
  SrcInfo,
} from './AgoraMediaPlayerTypes';

export interface IMediaPlayerSourceObserver {
  onPlayerSourceStateChanged_7fb38f1(
    state: MEDIA_PLAYER_STATE,
    reason: MEDIA_PLAYER_REASON
  ): void;

  onPositionChanged_303b92e(positionMs: number, timestampMs: number): void;

  onPlayerEvent_50f16fa(
    eventCode: MEDIA_PLAYER_EVENT,
    elapsedTime: number,
    message: string
  ): void;

  onMetaData_469a01b(data: Uint8Array, length: number): void;

  onPlayBufferUpdated_f631116(playCachedBuffer: number): void;

  onPreloadEvent_a1e3596(src: string, event: PLAYER_PRELOAD_EVENT): void;

  onCompleted(): void;

  onAgoraCDNTokenWillExpire(): void;

  onPlayerSrcInfoChanged_54f3e5a(from: SrcInfo, to: SrcInfo): void;

  onPlayerInfoUpdated_0e902a8(info: PlayerUpdatedInfo): void;

  onPlayerCacheStats_0145940(stats: CacheStatistics): void;

  onPlayerPlaybackStats_ffa466f(stats: PlayerPlaybackStats): void;

  onAudioVolumeIndication_46f8ab7(volume: number): void;
}
