/// Generated by terra, DO NOT MODIFY BY HAND.

export enum LOG_LEVEL {
  LOG_LEVEL_NONE = 0,
  LOG_LEVEL_INFO = 1,
  LOG_LEVEL_WARN = 2,
  LOG_LEVEL_ERROR = 4,
  LOG_LEVEL_FATAL = 8,
  LOG_LEVEL_API_CALL = 16,
  LOG_LEVEL_DEBUG = 32,
}

export enum LOG_FILTER_TYPE {
  LOG_FILTER_OFF = 0,
  LOG_FILTER_DEBUG = 2063,
  LOG_FILTER_INFO = 15,
  LOG_FILTER_WARN = 14,
  LOG_FILTER_ERROR = 12,
  LOG_FILTER_CRITICAL = 8,
  LOG_FILTER_MASK = 2063,
}

export class LogConfig {
  filePath?: string;

  fileSizeInKB?: number;

  level?: LOG_LEVEL;
}
