/// Generated by terra, DO NOT MODIFY BY HAND.

import { CallApiReturnType } from 'iris-web-core';

import {
  IMediaRecorderObserver,
  MediaRecorderConfiguration,
} from './AgoraMediaBase';

export interface IMediaRecorder {
  setMediaRecorderObserver_e1f7340(
    callback: IMediaRecorderObserver
  ): CallApiReturnType;

  startRecording_94480b3(config: MediaRecorderConfiguration): CallApiReturnType;

  stopRecording(): CallApiReturnType;
}
