name: Upload Release Asset

on:
  release:
    types: [created]

jobs:
  upload-assets:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup
        uses: ./.github/actions/setup

      - name: Setup Dependencies and Build
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

        run: |
          pnpm install
          pnpm run build
          RTC_PACKAGE_PATH=$(ls packages/rtc/dist | awk -F/ '{print $NF}')
          echo "RTC_PACKAGE_PATH=$RTC_PACKAGE_PATH" >> $GITHUB_ENV
          RTC_FAKE_PACKAGE_PATH=$(ls packages/fake/rtc/dist | awk -F/ '{print $NF}')
          echo "RTC_FAKE_PACKAGE_PATH=$RTC_FAKE_PACKAGE_PATH" >> $GITHUB_ENV

      - name: Update Artifact to Github Releases
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ./packages/rtc/dist/${{ env.RTC_PACKAGE_PATH }}
          asset_name: ${{ env.RTC_PACKAGE_PATH }}
          asset_content_type: application/javascript

      - name: Update Artifact to Github Releases
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ./packages/rtc/dist/${{ env.RTC_FAKE_PACKAGE_PATH }}
          asset_name: ${{ env.RTC_FAKE_PACKAGE_PATH }}
          asset_content_type: application/javascript
